### ISSUE TITLE
Error when disabling https

### ISSUE THREAD

**Issue by nacardin** [cn-terraform/terraform-aws-ecs-fargate-service#17] opened 2020-09-17 19:09 UTC
When using `cn-terraform/ecs-fargate/aws` version 2.0.19, if `lb_enable_https = false` is specified, it results in the following error:

```
Error: Invalid count argument

  on .terraform/modules/ecs-fargate.ecs-fargate-service/main.tf line 124, in resource "aws_security_group_rule" "ingress_through_https":
 124:   count                    = length(data.aws_lb_target_group.lb_https_target_groups)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

https://github.com/cn-terraform/terraform-aws-ecs-fargate-service/blob/1655307210d5b6aeac240c0731b51459afdd781d/main.tf#L124

**Comment by rredpoppy** [comment] 2020-09-23 14:47
hi guys. any update on this issue? running into this too

**Comment by jnonino** [comment] 2020-09-24 10:13
Duplicate of #13

**Closed** 2020-09-24 10:14 UTC
Labels: bug
